sup_email = "alugbinoluwaseyi1@gmail.com"
sqlusername = "oluwaseyi"
sqlpassword = "English2018"
defmail = "squadbytevoluteers@gmail.com"
mailuser = "squadbytevoluteers@gmail.com"
mailpass = "English2018"